                #HOW STRINGS ARE STORED...
s='karunakar'
print(id(s))
a='karunakar'
print(id(a))

m='karunakar'
print(id(m))
#Note:this all has same name so it has same reference id as well

#NOTE:STRINGS ARE IMMUTABLE...
#NOTE:VARIABLE ARE IMMUTABLE..
#NOTE:LIST WAS MUTABLE...

#NOTE:STRINGS ARE IMMUTABLE SINCE WE CAN CHANGE IT'S VALUE ONCE IT WAS ASSIGNED LIKE IN LISTS WE CAN CAN IT BY USING IT'S INDEX NUMBER BUT IN STRINGS WE CAN'T AND SAME FOR THE VARIABLES AS WELL..

#NOTE:WE HAVE TO CHANGE THEIR REFERENCES ONLY BUT WE CANNOT CHANGE THE STRING...

