# #CLASS METHOD IS JUST LIKE STATIC EVEN HERE ALSO NO NEED TO GIVE SELF AS LIKE THE STATIC HERE NEED TO  GIVE CLASS NAME(I.E ANY NAME UR WISH IT WONT BE USED ANYWHERE AND SOME PARAMETERS...)




# from datetime import date
# class student:
#     passingpercentage=40
#     def __init__(self,name,age=15,percentage=80):
#         self.name=name
#         self.age=age
#         self.percetage=percentage
        

#     @classmethod
#     def fromBirthYear(cls,name,year,percentage):
#         return cls(name,date.today().year-year,percentage)
    
#     def studentDetails(self):
#         print("name=",self.name)
#         print("age=",self.age)
#         print("percentage=",self.percetage)

# # s1=student("KKKKK")  #IN THIS CASE EVEN IF  U DONT GIVE IT WILL WORK.... SINCEE U CREATED A CLASS
# s1=student.fromBirthYear("parikh",1996,70)
# s1.studentDetails()
